### ISSUE TITLE
Tensorflow Version

### ISSUE THREAD

**Issue by 8carlosf** [facebookresearch/InferSent#1]
How can I convert the model to tensorflow or keras?
If I do so, is there a way to use the infersent.allnli.pickle pretrained model?
Also, I tried to use the pretrained model on a computer without a GPU, and it did not work, my mistake or is it supposed to run only on CUDA?

thanks,
great work!

**Comment by aconneau** [comment]
Hi, thanks for using this repo.

1) Why would you need to convert the model to tensorflow or keras?
In a python script, you can generate our sentence embeddings (in a numpy array) using our pytorch model, and use the obtained numpy array of embeddings as input for your tensorflow/theano/keras models for example. If you wanted to backpropagate through our network though (by finetuning) then you would need to use pytorch.

Because the question you ask is quite general : "how to convert a pytorch model (which the infersent.allnli.pickle is) to a tensorflow/keras model?" I am not sure it's currently possible, except by manually copying the weights.

2) For the CPU part, could you give more info about the exact bug you had? It's primarily supposed to run on GPU/Cuda yes (1000 sentences/s on GPU against 60 sentences/s on CPU). Though I'd like it to work also for CPU eventhough it's much smaller. Did you try to use "model.use_cuda=False" and "model.cpu()" as in "encoder/play.ipynb'". 
Thanks for your remarks.

**Comment by 8carlosf** [comment]
Sorry, I skipped the notebook :/
I did manage to make it work, I did have to do (otherwise it requires CUDA to load the model)
```
infersent = torch.load(relative_path('infersent.allnli.pickle'), map_location=lambda storage, loc: storage)
```
not sure what `map_location` mean, I'm not familiar with Torch.

I also patched the prints on `models.py` to make it python3 compatible (I will make a PR soon).

Thanks for the reply, it helped a lot :) I still would like to look into re-implementing this in Tensorflow, only because it is more popular and versatile (being able to train in python and deploy in another language is a big plus), but, for now this works just fine.

**Comment by aconneau** [comment]
Added a commented cell in encoder/play.ipynb to explain how to load the model on CPU-only.
Reimplementing train_nli.py and train the model in TensorFlow could definitely be useful for many users yes, if you feel like looking into it.
Indeed it needs to be made python3 compatible. Thanks again for your remarks.
