### ISSUE TITLE
torch.load import error

### ISSUE THREAD

**Issue by Sureya** [facebookresearch/InferSent#11]
I tried to follow the example code that was given, it gives the following error in Mac OS X, tried many posts, but no clear answer yet. any help would be appreciated.

> ImportError                               Traceback (most recent call last)
> <ipython-input-2-56ab4741a1a1> in <module>()
> ----> 1 infersent = torch.load('infersent.allnli.pickle')
> 
> .../lib/python2.7/site-packages/torch/serialization.pyc in load(f, map_location, pickle_module)
>     227         f = open(f, 'rb')
>     228     try:
> --> 229         return _load(f, map_location, pickle_module)
>     230     finally:
>     231         if new_fd:
> 
> .../lib/python2.7/site-packages/torch/serialization.pyc in _load(f, map_location, pickle_module)
>     375     unpickler = pickle_module.Unpickler(f)
>     376     unpickler.persistent_load = persistent_load
> --> 377     result = unpickler.load()
>     378
>     379     deserialized_storage_keys = pickle_module.load(f)
> 
> ImportError: No module named models
>

**Comment by 8carlosf** [comment]
The problem has to do with the way the model was saved. You need to keep the directory structure and can't load it without the encoder/models.py next to your code.
https://stackoverflow.com/questions/42703500/best-way-to-save-a-trained-model-in-pytroch
Because that wasn't ideal for me, what I did was load the model and pickle it again with the recommended method.
