### ISSUE TITLE
How to train on CPU ? 

### ISSUE THREAD

**Issue by ShivaliGoel** [facebookresearch/InferSent#29]
I tried changing use_cuda to False in train_nli.py and -gpu_id 0

**Comment by aconneau** [comment]
Hi, I'm afraid training such large Bi-LSTMs on CPU will just be too slow on a large dataset such as SNLI.
Though you can use the pre-trained model and generate sentence embeddings on CPU as explained here: https://github.com/facebookresearch/InferSent/blob/master/encoder/demo.ipynb

**Comment by karamat** [comment]
@aconneau approximately how much time it will take to train the model on CPU? with 2.6 GHz Intel Core i7 Processor and 8 GB RAM

**Comment by aconneau** [comment]
For the 2048 hidden size BiLSTM, it is just not feasible on CPU I think. For a 256 Bi-LSTM, I am not sure, I haven't checked. Train_nli.py should give you the number of sentences processed per second, so you could compare for the first batches how much time it takes (using either a GPU or a CPU) and check the speedup that GPU brings. The GPU is especially powerful since there is the CUDNN implementation of LSTMs..
It's like training a ConvNet on ImageNet with a CPU: unfortunately, that's not possible on large datasets and with large networks, that's why people have been using GPUs.
