### ISSUE TITLE
How to train the model on AllNLI (SNLI and MultiNLI) ?

### ISSUE THREAD

**Issue by wirehack** [facebookresearch/InferSent#41]
In the train code, it can only provide one dataset, but I want to train the model on both datasets (SNLI and MultiNLI). How should I do that?

**Comment by aconneau** [comment]
Hi,

"AllNLI" (in the paper) is defined as follows:

TRAIN = SNLI TRAIN + MultiNLI TRAIN
DEV = SNLI DEV + MultiNLI MATCHED
TEST = SNLI TEST + MultiNLI MISMATCHED

you can create the AllNLI dataset as follows after having downloaded the MultiNLI and SNLI datasets using "get_data.bash" (in InferSent/dataset)

```bash
mkdir AllNLI
cat SNLI/s1.train MultiNLI/s1.train > AllNLI/s1.train &
cat SNLI/s2.train MultiNLI/s2.train > AllNLI/s2.train &
cat SNLI/labels.train MultiNLI/labels.train > AllNLI/labels.train &

cat SNLI/s1.dev MultiNLI/s1.dev.matched > AllNLI/s1.dev &
cat SNLI/s2.dev MultiNLI/s2.dev.matched > AllNLI/s2.dev &
cat SNLI/labels.dev MultiNLI/labels.dev.matched > AllNLI/labels.dev &

cat SNLI/s1.test MultiNLI/s1.dev.mismatched > AllNLI/s1.test &
cat SNLI/s2.test MultiNLI/s2.dev.mismatched > AllNLI/s2.test &
cat SNLI/labels.test MultiNLI/labels.dev.mismatched > AllNLI/labels.test &
```

Finally, in train_nli.py, modify the command ["nlipath"](https://github.com/facebookresearch/InferSent/blob/master/train_nli.py#L29) so that it points to 'dataset/AllNLI'.
